title: Stephen Barr
description: Official website of Stephen Barr - higher education leader, professional portfolio, and contact information.
author: stephenabarr.com
url: https://stephenabarr.com
google_analytics: G-V745RLVFR1
social_image: /images/SBarr-Headshot-VCU.jpg
linkedin_url: https://www.linkedin.com/in/stephenabarr/
formspree_endpoint: https://formspree.io/f/stephen@stephenabarr.com
formspree_form_id:
